[package]
name = "floodfile"
version = "1.0.0"
edition = "2021"

[dependencies]
crossbeam = "0.8.4"
cursive = {version = "0.21.1", features = ["toml"]}
lz4_flex = "0.11.3"
md5 = "0.7.0"
pnet = "0.35.0"
rand = "0.8.5"
thiserror = "2.0.11"
