shadow = false
borders = "outset"  

[colors]
background = ""
view       = "black"

title_primary = "white"
highlight = "#7B68EE"
highlight_inactive = "#7B68EE"

primary   = "white"
secondary = "#F5F5F5"
tertiary  = "white"
